export const MULTISIG_VAULT_CONTRACT_ADDRESS =
  "0x412F1c3AC59AFc5bE13A94E61b2cA2b872e630a5";

export const VAULT_TOKEN_CONTRACT_ADDRESS =
  "0x6554D741B40Ff061c59c1c3C9Eb4BA98e4B3d351";

export const MULTISIG_VAULT_ABI = [
  {
    anonymous: null,
    name: null,
    inputs: [],
    outputs: [],
    type: "constructor",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "OwnershipTransferred",
    inputs: [
      { internalType: "address", name: "previousOwner", type: "address" },
      { internalType: "address", name: "newOwner", type: "address" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "RoleAdminChanged",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "bytes32", name: "previousAdminRole", type: "bytes32" },
      { internalType: "bytes32", name: "newAdminRole", type: "bytes32" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "RoleGranted",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "sender", type: "address" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "RoleRevoked",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "sender", type: "address" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "SignerLimitChange",
    inputs: [{ internalType: "uint256", name: "signerLimit", type: "uint256" }],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "TransactionCompleted",
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "unlockTime", type: "uint256" },
      { internalType: "uint256", name: "transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "TransactionCreated",
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "unlockTime", type: "uint256" },
      { internalType: "uint256", name: "transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "TransactionRejected",
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "TransactionSigned",
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "SIGNER",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "addTransaction",
    inputs: [
      { internalType: "address payable", name: "_to", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_unlockTime", type: "uint256" },
    ],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "balance",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "connectToOtherContracts",
    inputs: [
      { internalType: "address[]", name: "contracts", type: "address[]" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "emergencyWithdraw",
    inputs: [],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "executeTransaction",
    inputs: [
      { internalType: "uint256", name: "_transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "getConfirmationCount",
    inputs: [
      { internalType: "uint256", name: "_transactionId", type: "uint256" },
    ],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getConfirmations",
    inputs: [
      { internalType: "uint256", name: "_transactionId", type: "uint256" },
    ],
    outputs: [
      { internalType: "address[]", name: "_confirmations", type: "address[]" },
    ],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getRoleAdmin",
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getRoleMember",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    outputs: [{ internalType: "address", name: "", type: "address" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getRoleMemberCount",
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getTransactionCount",
    inputs: [
      { internalType: "bool", name: "pending", type: "bool" },
      { internalType: "bool", name: "executed", type: "bool" },
    ],
    outputs: [{ internalType: "uint256", name: "count", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "grantRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "hasRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "owner",
    inputs: [],
    outputs: [{ internalType: "address", name: "", type: "address" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "rejectTransaction",
    inputs: [
      { internalType: "uint256", name: "_transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "renounceRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "revokeRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "setSignerLimit",
    inputs: [
      { internalType: "uint256", name: "_signerLimit", type: "uint256" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "signTransaction",
    inputs: [
      { internalType: "uint256", name: "_transactionId", type: "uint256" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "signerLimit",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "supportsInterface",
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "token",
    inputs: [],
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "transactions",
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    outputs: [
      { internalType: "address payable", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "unlockTime", type: "uint256" },
      { internalType: "uint256", name: "signatureCount", type: "uint256" },
      { internalType: "bool", name: "executed", type: "bool" },
    ],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "transferOwnership",
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
];

export const VAULT_TOKEN_ABI = [
  {
    anonymous: null,
    name: null,
    inputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "symbol", type: "string" },
    ],
    outputs: [],
    type: "constructor",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "Approval",
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "Paused",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "RoleAdminChanged",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "bytes32", name: "previousAdminRole", type: "bytes32" },
      { internalType: "bytes32", name: "newAdminRole", type: "bytes32" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "RoleGranted",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "sender", type: "address" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "RoleRevoked",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
      { internalType: "address", name: "sender", type: "address" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "Transfer",
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
    ],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "Unpaused",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [],
    type: "event",
    stateMutability: null,
  },
  {
    anonymous: null,
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "MINTER_ROLE",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "PAUSER_ROLE",
    inputs: [],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "allowance",
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "approve",
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "balanceOf",
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "burn",
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "burnFrom",
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "decimals",
    inputs: [],
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "decreaseAllowance",
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "subtractedValue", type: "uint256" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "getRoleAdmin",
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getRoleMember",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    outputs: [{ internalType: "address", name: "", type: "address" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "getRoleMemberCount",
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "grantRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "hasRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "increaseAllowance",
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "addedValue", type: "uint256" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "mint",
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "name",
    inputs: [],
    outputs: [{ internalType: "string", name: "", type: "string" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "pause",
    inputs: [],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "paused",
    inputs: [],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "renounceRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "revokeRole",
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "supportsInterface",
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "symbol",
    inputs: [],
    outputs: [{ internalType: "string", name: "", type: "string" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "totalSupply",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    type: "function",
    stateMutability: "view",
  },
  {
    anonymous: null,
    name: "transfer",
    inputs: [
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "transferFrom",
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    type: "function",
    stateMutability: "nonpayable",
  },
  {
    anonymous: null,
    name: "unpause",
    inputs: [],
    outputs: [],
    type: "function",
    stateMutability: "nonpayable",
  },
];